sudo: false
language: node_js
node_js:
  - "6"
  - "5"
script: npm run-script test
deploy:
  provider: npm
  email: tech@cargomedia.ch
  api_key:
    secure: AaSR6snRojLs4vjHQf2gRclggSX58EYiPY+v7b8UBGuQhy+bBjgE621Ne8SWyBAN9JZId8rYOGfT3mXIMNolFHqNZubqd8Y7nc1sNhni+f+NZLVpGp0lXSvxNoJ582f2epyMssu+ad22s2vsr2hZbC3TuwIrvA6yHqeSdigJE3w=
  on:
    tags: true
    repo: cargomedia/hubot-pulsar
